### ISSUE TITLE
Support while statement's compilation

### ISSUE THREAD

**Issue by st0012** [rooby-lang/rooby#32]

**Comment by hzlmn** [comment]
@st0012 Are you working on it, can help with it if no?

**Comment by st0012** [comment]
@hzlmn Hi I already worked on that and just opened a PR #41. But for now I just added some test cases an not actually implemented yet. And I think I will deal with other issues first so you can continue my job if you have a plan to implement it.

**Comment by hzlmn** [comment]
@st0012 ok, gonna look on it, just a question do you plan to implement `ruby` styled while loop, because if so then semicolon [here](https://github.com/rooby-lang/rooby/pull/41/files#diff-6cf324a7946500f3f5aecc1d7c471e44R286) not important and can be omitted. Is it make sense for you?

**Comment by st0012** [comment]
@hzlmn Hi, it's because the limit of parser, see [here](https://github.com/rooby-lang/rooby/wiki/Special-syntaxes). But if you can implement it without this workaround surely would be better.

**Comment by st0012** [comment]
This feature is already implemented by @janczer so I'm closing it.
