### ISSUE TITLE
Write homebrew formula

### ISSUE THREAD

**Issue by st0012** [rooby-lang/rooby#71]

**Comment by adlerhsieh** [comment]
Do you mean that users can install this language through the following commands?

```
brew tap rooby-lang/rooby
brew install rooby
```

If so, I can help on this. Create a `rooby-lang/homebrew-rooby` repository with a `README.md` file. I'll send a pull request with a formula to that.

**Comment by st0012** [comment]
@adlerhsieh Yes this is what I mean. What will you need for this?  A new repo?

**Comment by adlerhsieh** [comment]
Yes. A new repo with name `homebrew-rooby`, and with 1 commit with any file (cannot send a pull request to blank repo).

**Comment by st0012** [comment]
@adlerhsieh Just created the repo and added you as a member.

**Comment by adlerhsieh** [comment]
Formula updated. It can be installed as long as we release the first version (or we can release a `0.0.1` version to test it out if you want).

Also, just to confirm, in the [README](https://github.com/rooby-lang/homebrew-rooby) I specify that there should be a `/bin/rooby` binary file in the repository. This allows users to use Rooby without having to install Go beforehand. Is this something you expect?

**Comment by st0012** [comment]
Yes, thanks for your help!

**Comment by st0012** [comment]
Thanks to @adlerhsieh now we have our first release(v0.0.1)! And I'm able to close this 😁
